import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { style } from "./gallerie/index";

export default function Home() {
  async function appel() {
    const response = await fetch("api/hello");
    const res = await response.json();
    console.log(res);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Pompom4Ever</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <b style={style.text}>LE</b> Accueil
        </h1>
      </main>
    </div>
  );
}
/*
<a href={"/gallerie"}>
<button>Go à la gallerie</button>
</a>
*/
